### ISSUE TITLE
Stag.Factory can only be used with a single Gson instance

### ISSUE THREAD

**Issue by mcumings** [vimeo/stag-java#112]
#### Issue Summary

Stag.Factory is stateful which can cause problems when attempting to use a Stag.Factory
instance across multiple GsonBuilder invocations.

#### Reproduction Steps

Create a Stag.Factory instance A.
Create a TypeAdapter implementation B mapping java.util.Date.
Create a TypeAdapter implementation C mapping java.util.Date.
Create a type D to marshal that has a java.util.Date field in it.

Create a Gson instance using a builder configured with A and B.
Create a Gson instance using a builder configured with A and C.

The first Gson instance used to marshal/unmarshal type D will set a private field in A to cache the TypeAdapter instance.  If the second Gson instance is then used then the type adapter lookup is skipped in favor of the previously cached instance coming from the alternate Gson instance.

#### Expected Behavior

The current behavior is an implicit result of performance optimizations.  Given that reuse of a
Stag.Factory instance is a corner case the current behavior is probably reasonable.  I'm raising this
as an issue to document and highlight this surprising result to see if we want to do anything
about it.  For instance, it would be possible to capture the initial Gson instance used and then assert instance equality for subsequent uses rather than fail later in the process.

#### Actual Behavior

Described above.

**Comment by anthonycr** [comment]
Added a test case in https://github.com/vimeo/stag-java/tree/bug/stateful-factory

**Comment by anthonycr** [comment]
I'm thinking maybe we should just throw an exception if you try to reuse a factory with multiple gson instances. That seems like the best approach, what are your thoughts? What I would do is have the following in every method of the factory:

```java
private Gson mGson;

TypeAdapter<Blah> someMethodThatReturnsTypeAdapterBla(Gson gson) {
    setOrThrow(gson);

    return blah;
}

setOrThrow(Gson gson) {
    if (mGson != gson) {
        if (mGson != null) {
            throw new UnsupportedOperationException("This factory can only be used with a single Gson instance, please create a new instance");
        }

        mGson = gson;
    }
}
```

Now on the other hand, we could fix it so that it works with multiple instances, and I see two obvious options for allowing a factory to be used by multiple gson instances, but they both seem bad:
- Save off the gson instance when the `getMyClassTypeAdapter` method gets called, and if they are not the same, return a new type adapter. There would be a big problem performance-wise though, because if you are using two different gson instances with two different type adapters for a certain type simultaneously, then the gson instance would be changing all the time and it would always be recreating the type adapter. 
- Hold a map of type adapters to gson objects within the stag factory. This would allow each gson instance to have its own type adapter and would prevent type adapters from being recreated all the time, but it has the problem of keeping all the gson instances in memory (maybe this isn't a problem though). It's complicated to implement.

**Comment by mcumings** [comment]
I agree with your assessment.  I think it's a corner case so supporting an option which fails fast rather than subtly failing later seems like the best option, rather than supporting it explicitly.  I think the setOrThrow option would be the easiest win as it lets the consumers know why it is failing and still has a light implementation cost.

If we add support for this now, removing support becomes difficult.  If we make it fail-fast we retain the option to add explicit support in code at a later time should this prove to be less of a corner case than initially anticipated.

Thanks for taking a look at it.  I mainly wanted to raise visibility to the issue on the interwebs so others might be able to benefit from the painful RCCA. :)

**Comment by anthonycr** [comment]
Okay great, I'll make this change 👍

**Comment by anthonycr** [comment]
Closing as fixed, I will be releasing an update with this change soon.

**Comment by mcumings** [comment]
Awesome.  Thanks, dude!
