### ISSUE TITLE
Should support boolean "isXXXX()" getter naming convention

### ISSUE THREAD

**Issue by brentwatson** [vimeo/stag-java#126]
#### Issue Summary
JavaBean naming convention is to use `isXXXX()` for boolean fields.  Stag currently only supports `getXXXX()`.

#### Reproduction Steps
Attempt to generate code for a boolean field with a `is` getter.  Results in a error.

#### Expected Behavior
Should support `is` getters

#### Actual Behavior
Fails to generate code.  Outputs a "cannot find getter/setter" error message.

**Comment by anthonycr** [comment]
Since we will be supporting `isXXXX` in **addition** to `getXXXX` for boolean fields, rather than replacing current naming, we need to establish the priority for the getters. My proposal is to prioritize the JavaBean method first, with the standard getter being lower priority. Given the following field:
```java
boolean test;
```
We will first look for a method with the name `isTest` and the return type of `boolean`.
```java
boolean isTest() { ... }
```
If a test with that name and return type is not found (i.e. if no method with name `isTest` is found or if the return type of `isTest` is not boolean), we will fall back to looking for `getTest`.
```java
boolean getTest() { ... }
```
If the `getTest` method is not found or it is found but does not have a boolean return type, then an error will be thrown as is current behavior.

Setters will be unaffected by this, and no other types aside from primitive `boolean` will use this naming change.

One quick clarification, are `Boolean` (object) fields subject to the same JavaBean naming conventions? I think not since they are objects and can potentially be null, but just want to make sure we are on the same page.

**Comment by brentwatson** [comment]
@anthonycr Yup, I agree that `is` methods should take priority if they are found.  And, yes, `Boolean` fields should always use `get` never `is`.

**Comment by anthonycr** [comment]
Closing, fixed by https://github.com/vimeo/stag-java/pull/127
