### ISSUE TITLE
Generated TypeAdapter writes out an empty object for null values

### ISSUE THREAD

**Issue by mcumings** [vimeo/stag-java#132]
#### Issue Summary

When the generated TypeAdapter is instructed to write a `null` value it always writes an empty object.  This is due to the following code at the beginning of the `write(JsonWriter, T)` method:
```
    writer.beginObject();
    if (object == null) {
      writer.endObject();
      return;
    }
``` 

#### Reproduction Steps

Create a type adapter and use it to write a `null` value.

#### Expected Behavior

The generated TypeAdapter should wither write out a JSON null in this scenario or should be configurable to allow either behavior at the discretion of the user.

#### Actual Behavior

A JSON Object with no fields is written.

**Comment by mcumings** [comment]
Raising this for discussion as to how we should handle this.  Our app has code which expects to write a JSON null in this scenario.

We could add an option to @UseStag to allow the user to declare the desired behavior, defaulting operation to writing an empty object.  Any opinion on this?

**Comment by anthonycr** [comment]
@mcumings I think this falls squarely in the realm of a bug. I can't think of any reason why it would be advantageous to write an empty object rather than a null object in this scenario, and I would assume this would cause problems for parsing in most cases where a field could be null, but the fields in the object are annotated `@NotNull` or something and therefore an object which succeeds to be written to JSON would fail to be read from the same JSON.

Unless anyone else thinks otherwise, I would advocate for just switching the behavior completely and putting the change behind a minor version bump.

**Comment by anthonycr** [comment]
Another bug I found, if you have an array with a null value, it will emit an empty array instead of null. I am fixing those as well.

**Comment by anthonycr** [comment]
See: https://github.com/vimeo/stag-java/pull/133

**Comment by mcumings** [comment]
Sorry for the delay in getting back to this and thanks for already taking a stab at it!

I think we're safe after this change with respect to the ingress of nulls.  I think your final suggestion relates only to writing the null values in which case there are only two scenarios that I can think of:

1. The root object or array being marshalled is null.  I think we have no choice other than to write the null there.  This is the scenario being handled in this issue.
1. A non-null object is attempting to write a null field.  Currently this no-ops and skips that field.  I think this is the only point where additional configuration could be applied to select whether or not to actually write a null value versus just skipping it.

I don't think I personally have a need/desire for flagging a forced write of null in that latter case.  However, I think it boils down to the principle of being broad in what you accept and specific in what you emit and the inevitable violations of the same.  I'm sure a system exists somewhere that does not adhere to that principle and would expect the field to always be present, even if null.

**Comment by anthonycr** [comment]
Thanks for replying, I'm going to open up a new issue which pertains to configuration of writing null values to JSON instead of skipping them. A scenario where this configuration could be needed would be where a class has fields with default values, so setting the field to null and then reading it out of JSON would cause a mismatch in equality.

**Comment by anthonycr** [comment]
Closing as fixed
