### ISSUE TITLE
Support for a class level annotation

### ISSUE THREAD

**Issue by yasirmhd** [vimeo/stag-java#27]
#### Issue Summary
Now that Stag has support for Generics, Enums, Maps etc it can generate a type adapter for pretty much any class. With the current approach of having to provide GsonAdapterKey is a huge friction for people to move to this library from Gson.

We can have another annotation maybe at a class level called @UseStag. We have some sort of implementation for this already in place.

**Comment by anthonycr** [comment]
Great idea, such an annotation could maybe replace the current usage of the `@GsonAdapterKey` annotation at the class level (currently used to tell stag about a class that doesn't have any annotated fields but inherits from a class with annotated fields).

This should be simple to implement. 

Let's solidify the spec:
- name the new annotation `@UseStag`
- annotation is only applicable at the class level
- annotation replaces current usage of `@GsonAdapterKey` at the class level
- `@GsonAdapterKey` will no longer be allowed to be applied at the class level
- annotation will cause stag to generate a type adapter with all the fields in the annotated class, regardless of whether or not they are annotated with `@GsonAdapterKey`
- fields in a class annotated with `@UseStag` that are **also** annotated with `@GsonAdapterKey` will use the value passed by that annotation for the json key rather than the field name.

Look good or should any changes be made to this spec? Possibly, the `@GsonAdapterKey` behavior at the class level should be left, in case the consumer wants to generate a type adapter for a class inheriting from another class, but doesn't want any of the fields in the annotated class filled. Or maybe there could be an optional boolean that could be passed to `@UseStag` that specified whether only the parent's fields should be considered

**Comment by yasirmhd** [comment]
Sounds good. The only slight addition that I will like to propose is to give support for SerializedName for JSON name
