### ISSUE TITLE
Stag generates type adapters for non-annotated nested classes

### ISSUE THREAD

**Issue by mcumings** [vimeo/stag-java#73]
#### Issue Summary

Given the class:
```
@UseStag
public class NestedClassWithoutUseStag {

    String field;

    /**
     * No adapter should be created for this class.
     */
    public static class NestedWithoutUseStag {

    }
}
```

Stag is generating TypeAdapter implementations for the outer class (`NestedClassWithoutUseStag`) as expected but is also generating a TypeAdapter for the nested, unannotated class (`NestedWithoutUseStag`).  This is unexpected as it makes a fairly broad assumption of the nature of the nested class in that it assumes it is structurally related to the model/entity class and - for instance - is not a nested JsonDeserializer / JsonSerializer / TypeAdapter implementation.

This additionally causes problems if some of the fields of the top level class are of types defined as nested inner classes but have a custom type adapter registered with Gson.  Because Stag is automatically generating the type adapters for the nested class the nested class becomes known to Stag and the Gson type adapter lookup is bypassed.

#### Expected Behavior

Expected behavior would be that classes need to be explicitly annotated with @UseStag in order for a TypeAdapter to be generated.

#### Actual Behavior

Nested classes have TypeAdapters generated as with the FieldOption.ALL option.  This looks to be explicitly added in  88ab69f81aa15ae4f8ad321ba411a8c909e49c4e with commit comment `Fixed backwards incompatibility, fixed nested classes always defaulting to fieldoption.all`.

Raising this as an issue so that we can discuss whether this makes sense and/or address the issue via other means.

**Comment by mcumings** [comment]
@anthonycr - Want to get your opinion on this as you have some context on the original spec and the addition of this backwards compatibility change.

One potential solution might be to add a `FieldOptions.INHIBIT` to specifically mark classes which should under no circumstances cause code to be generated but this feels clunky to me.  It would make better sense to me to drop the backwards compatibility change, given that @UseStag was intended to be allowed as a breaking change.

**Comment by anthonycr** [comment]
@mcumings yeah, so the original spec was that inner classes would inherit the annotation from the outer classes. I'm not sure it was ever discussion about it. I think what happened is that with the original `@UseStag` implementation the inner classes were also picked up by the annotation processor and processed, probably by accident. Really it should have been viewed as a bug, but after it was already in, I thought it was convenient and just decided to fix the bug seen in that commit. 

In hindsight this was a bad thing to add because now it introduces the need for a `FieldOptions.IGNORE` or something, which is both clunky and confusing considering that there is a `FieldOptions.NONE` option which just marks the class but ignores all fields in the immediate class. We've already run into the need for such an option in our networking layer because we have some enums in model classes that don't need adapters generated for them. I think I agree with you that the best thing to do moving forward would be to drop the functionality completely and explicitly require `@UseStag` in order for an adapter to be generated. I also just realized that the nested class generation isn't even documented in the readme, so I'm even more okay with removing the functionality. It saves the need to create another enum `FieldOptions`.

I'm in the process of completely removing the `@GsonAdapterKey` annotation in this branch (https://github.com/vimeo/stag-java/tree/removing-gsonadapterkey) , so the release that that goes into will be contain semi-breaking changes and I'll have to version accordingly. So, I think we can get this change into that breaking release as well. I plan to start merging the breaking change of removing gson adapter key early next week, as I want to make sure that 2.0.2 doesn't need any immediate bug fixes before I start merging into dev.

**Comment by mcumings** [comment]
Okay, sounds good.  I wonder if the Flipkart folks would agree with our assessment on this?
@anirudhramanan, do you folks have any reservations about removing the implicit adapter generation for un-annotated nested classes?

**Comment by anirudhramanan** [comment]
Adding another enum to FieldOptions might be confusing as we already have NONE option to ignore the member fields for a class. I think the classes (including the nested ones) should be marked with @UseStag annotation for its type adapter to be generated. This would make it more cleaner

cc: @yasirmhd

**Comment by mcumings** [comment]
Okay, I put up https://github.com/vimeo/stag-java/pull/76 with proposed logic/functional changes.

We have a choice here with respect to how we handle nested classes that inherit annotations from higher up in the type hierarchy.  In the pull request I implemented it such that these classes would retain type adapter generation though I can envision it going either way.

One reason that perhaps might justify selecting the alternate approach would be if incremental compilation did not result in the annotation processor receiving notification of concrete classes being changed when the base class is modified. I haven't been able to test this yet.

**Comment by mcumings** [comment]
Okay, the more I think about it the more I think my original approach which automatically searched base classes for the `@UseStag` annotation is not the right way to go.  I updated my PR with updated logic which only generates type adapter code for classes explicitly annotated.

While both approaches work and can be rationalized, I think automatically searching the type hierarchy violates the principle of least surprise, all the while not buying much (if anything) from a library UX perspective.

**Comment by anthonycr** [comment]
Sorry I haven't commented on this in a while. I think you made the right choice with excluding classes that are not annotated but that inherit from annotated classes 👍

**Comment by anthonycr** [comment]
Closing as fixed.
