### ISSUE TITLE
Why not auto-value-gson?

### ISSUE THREAD

**Issue by darktiny** [vimeo/stag-java#8]
https://github.com/rharter/auto-value-gson

It also provide null check which is useful for me at least.

**Comment by anthonycr** [comment]
`auto-value-gson` eliminates reflection like stag, but it requires you to use AutoValue, which we aren't using. Stag also provides null checks. If you're trying to eliminate reflection and you're using AutoValue, then you must use auto-value-gson, if you aren't then you would use stag.

There are other differences in the implementations, one of which is that stag can generate type adapters for model objects that inherit from each other, while auto-value-gson does not (due to AutoValue prohibiting model objects inheriting from each other).

closing this issue. Let me know if you have other questions by commenting here or opening a new issue
